services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: msql-nlw
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - '3336:3306'
    networks:
      - my-networks
networks:
  my-networks:
    driver: bridge
    